/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import {awsconfig} from './awsconfig'
const awsmobile = {
    ...awsconfig,
    "oauth": {},
};

export default awsmobile;
