/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cognito_identity_pool_id": "eu-north-1:8dda40e9-e338-4861-ae5a-3a1e42565751",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_jOvUM4kOv",
    "aws_user_pools_web_client_id": "3hbt52g7tep7ddc72teo9u71r7",
    "oauth": {}
};


export default awsmobile;
