/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// NEXT_PUBLIC_aws_project_region=eu-central-1
// NEXT_PUBLIC_aws_cognito_identity_pool_id=eu-central-1:17a051c2-4123-4e39-bff1-d6f59d260312
// NEXT_PUBLIC_aws_cognito_region=eu-central-1
// NEXT_PUBLIC_aws_user_pools_id=eu-central-1_gf5yCYAwz
// NEXT_PUBLIC_aws_user_pools_web_client_id=1bhg379ma76l26c3s2gvk6ms71
// oauth={}
export const awsconfig = {
    "aws_project_region": process.env.aws_project_region,
    "aws_cognito_identity_pool_id": process.env.aws_cognito_identity_pool_id,
    "aws_cognito_region": process.env.aws_cognito_region,
    "aws_user_pools_id": process.env.aws_user_pools_id,
    "aws_user_pools_web_client_id": process.env.aws_user_pools_web_client_id,
    "oauth": {}
};


